language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip

install: 
- pip install -r requirements-devel.txt
- pip install pytest-cov coveralls
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi

script: py.test --cov atomicapp_builder
after_success: coveralls
